### 
GET http://localhost:3001/api/persons

###
DELETE http://localhost:3001/api/persons/7

###
POST http://localhost:3001/api/persons
Content-type: application/json

{
    "name": "yes",
    "number": "123456789"
}

###
GET http://localhost:3001/api/persons
