services:
  - type: web
    name: fullstack-app
    env: node
    plan: free
    rootDir: 3.10 tehtävä nettiin
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    envVars:
      - key: NODE_ENV
        value: production
